# Generated by Django 5.1.4 on 2024-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('data_of_birth', models.DateField()),
                ('phone_number', models.BigIntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
