# Generated by Django 5.1.4 on 2025-01-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadline_data',
            new_name='deadline_date',
        ),
    ]
