# Generated by Django 5.1.4 on 2025-01-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='todo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='desc_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
