# Generated by Django 5.1.4 on 2025-01-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_delete_author_delete_todo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
